# Generated by Django 6.0.3 on 2026-03-26 10:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Ожидание'), ('in_progress', 'Идёт игра'), ('finished', 'Завершена')], default='waiting', max_length=16)),
                ('subjects', models.JSONField(default=list)),
                ('task_count', models.PositiveSmallIntegerField(default=5)),
                ('max_players', models.PositiveSmallIntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('first_name', models.CharField(max_length=128)),
                ('total_score', models.IntegerField(default=0)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Telegram-пользователь',
                'verbose_name_plural': 'Telegram-пользователи',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('finished', 'Завершена')], default='active', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='game.room')),
            ],
            options={
                'verbose_name': 'Игровая сессия',
                'verbose_name_plural': 'Игровые сессии',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct_answer', models.CharField(blank=True, max_length=512, null=True)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('subject', models.CharField(choices=[('math', 'Математика'), ('russian', 'Русский язык'), ('physics', 'Физика'), ('chemistry', 'Химия'), ('biology', 'Биология'), ('history', 'История'), ('social', 'Обществознание'), ('informatics', 'Информатика'), ('english', 'Английский язык'), ('geography', 'География'), ('literature', 'Литература')], max_length=20)),
                ('task_type', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'indexes': [models.Index(fields=['subject', 'task_type'], name='game_task_subject_31f42d_idx'), models.Index(fields=['subject', 'difficulty'], name='game_task_subject_6e031a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('time_limit', models.PositiveSmallIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_tasks', to='game.gamesession')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.task')),
            ],
            options={
                'verbose_name': 'Задача в сессии',
                'verbose_name_plural': 'Задачи в сессиях',
                'ordering': ['order'],
                'unique_together': {('session', 'order'), ('session', 'task')},
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='tasks',
            field=models.ManyToManyField(through='game.SessionTask', to='game.task'),
        ),
        migrations.AddField(
            model_name='room',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rooms', to='game.telegramuser'),
        ),
        migrations.CreateModel(
            name='TaskAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.task')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['order'],
                'unique_together': {('task', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=512)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='game.task')),
            ],
            options={
                'verbose_name': 'Изображение к задаче',
                'verbose_name_plural': 'Изображения к задачам',
                'ordering': ['order'],
                'unique_together': {('task', 'order')},
            },
        ),
        migrations.CreateModel(
            name='RoomPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_difficulty', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=2)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.room')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_entries', to='game.telegramuser')),
            ],
            options={
                'verbose_name': 'Игрок в комнате',
                'verbose_name_plural': 'Игроки в комнатах',
                'unique_together': {('room', 'player')},
            },
        ),
        migrations.CreateModel(
            name='PlayerSessionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('wrong_count', models.PositiveSmallIntegerField(default=0)),
                ('skipped_count', models.PositiveSmallIntegerField(default=0)),
                ('place', models.PositiveSmallIntegerField(null=True)),
                ('chosen_difficulty', models.PositiveSmallIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='game.gamesession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='game.telegramuser')),
            ],
            options={
                'verbose_name': 'Итог игрока за сессию',
                'verbose_name_plural': 'Итоги игроков за сессии',
                'unique_together': {('session', 'player')},
            },
        ),
        migrations.CreateModel(
            name='PlayerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_answer', models.CharField(blank=True, max_length=512, null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('score_delta', models.SmallIntegerField(default=0)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game.gamesession')),
                ('session_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game.sessiontask')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game.telegramuser')),
            ],
            options={
                'verbose_name': 'Результат игрока',
                'verbose_name_plural': 'Результаты игроков',
                'unique_together': {('session', 'player', 'session_task')},
            },
        ),
    ]
