# Generated by Django 6.0.3 on 2026-03-28 11:20

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessiontask',
            unique_together={('session', 'task')},
        ),
        migrations.AlterField(
            model_name='room',
            name='subjects',
            field=models.JSONField(default=game.models.default_subjects),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.CharField(choices=[('math', 'Математика'), ('russian', 'Русский язык'), ('physics', 'Физика'), ('social', 'Обществознание'), ('informatics', 'Информатика')], max_length=20),
        ),
    ]
