# Generated by Django 6.0.3 on 2026-03-28 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_sessiontask_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='game.room'),
        ),
    ]
